update publish workflow-action

diff --git a/.github/workflows/publish-nuget.yml b/.github/workflows/publish-nuget.yml
--- a/.github/workflows/publish-nuget.yml
+++ b/.github/workflows/publish-nuget.yml
@@ -37,34 +37,48 @@ jobs:
       - name: Create NuGet Package
         run: dotnet pack --configuration Release
 
-      - name: Set Version and Package Path
-        id: vars
-        run: |
-          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
-          PACKAGE_PATH=$(find bin/Release -name "*.nupkg" | head -n 1)
-          echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV
-          echo "PACKAGE_NAME=$(basename "$PACKAGE_PATH")" >> $GITHUB_ENV
-        shell: bash
+      - name: Set VERSION
+        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
 
       - name: Push To NuGet Gallery
         run: |
-          dotnet nuget push "$PACKAGE_PATH" \
-            --source https://api.nuget.org/v3/index.json \
-            --api-key ${{ secrets.NUGET_API_KEY }} \
-            --skip-duplicate
+          dotnet nuget push "bin/Release/*.nupkg" \
+          --source https://api.nuget.org/v3/index.json \
+          --api-key ${{ secrets.NUGET_API_KEY }} \
+          --skip-duplicate
 
       - name: Push To GitHub Packages
-        run: |
-          dotnet nuget push "$PACKAGE_PATH" \
-            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
-            --api-key ${{ secrets.GH_API_SECRET }} \
-            --skip-duplicate
+        run: dotnet nuget push "bin/Release/*.nupkg" \
+          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
+          --api-key ${{ secrets.GH_API_SECRET }} \
+          --skip-duplicate
 
-      - name: Create GitHub Release and Upload Asset
-        uses: softprops/action-gh-release@v1
+      - name: Create GitHub Release
+        id: create_release
+        uses: actions/create-release@v1.1.4
         with:
           tag_name: ${{ github.ref }}
-          name: Release ${{ github.ref }}
-          files: ${{ env.PACKAGE_PATH }}
+          release_name: ${{ github.ref }}
+          draft: false
+          prerelease: false
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_API_SECRET }}
+
+      - name: Delete existing asset
+        env:
+          GH_TOKEN: ${{ secrets.GH_API_SECRET }}
+        run: |
+          gh release view ${{ github.ref_name }} \
+          --json assets -q '.assets[].name' | grep "Blazor.Editor.${{ env.VERSION }}.nupkg" && \
+          gh release delete-asset ${{ github.ref_name }} "Blazor.Editor.${{ env.VERSION }}.nupkg" \
+          --yes || echo "Asset not found"
+
+      - name: Upload Release Asset
+        uses: actions/upload-release-asset@v1.0.2
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: bin/Release/Blazor.Editor.${{ env.VERSION }}.nupkg
+          asset_name: Blazor.Editor.${{ env.VERSION }}.nupkg
+          asset_content_type: application/octet-stream
         env:
           GITHUB_TOKEN: ${{ secrets.GH_API_SECRET }}
